[package]
name = "web-leptos"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
leptos = { version = "0.6.14", features = ["csr"] }
shared = { version = "0.1.0", path = "../shared" }
