[workspace]
resolver = "1"
members = [ "crux_geolocation","shared", "shared_types", "web-leptos"]

[workspace.package]
authors = ["Tage Johansson"]
edition = "2021"
#repository = "https://github.com/redbadger/crux/"
license = "GPL-3.0-or-later"
keywords = ["crux", "crux_core", "cross-platform-ui", "ffi", "wasm"]

[workspace.dependencies]
anyhow = "1.0.86"
crux_core = "0.8.1"
serde = { version = "1.0.209", features = ["derive"] }
