[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
crux_core.workspace = true
serde.workspace = true
uniffi = { version = "0.28.1", features = ["build", "cli"] }
wasm-bindgen = "0.2.93"

[build-dependencies]
uniffi = { version = "0.28.1", features = ["build", "cli"] }
