[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
chrono.workspace = true
compact_str = { version = "0.8.0", features = ["serde"] }
crux_core.workspace = true
crux_geolocation = { version = "0.1.0", path = "../crux_geolocation" }
jord.workspace = true
rstar = "0.12.0"
serde.workspace = true
smallvec = { version = "1.13.2", features = ["serde"] }
uniffi = { version = "0.28.1", features = ["build", "cli"] }
wasm-bindgen = "0.2.93"

[build-dependencies]
uniffi = { version = "0.28.1", features = ["build", "cli"] }
